### ISSUE TITLE
Add doesn't work

### ISSUE THREAD

**Issue by JGAntunes** [sinfo/eventdeck#228]
Add companies & speakers isn't working. We're sending junk to the server (communications & comments).

**Comment by xicombd** [comment]
Wasn't this alteado faxina that bug? https://github.com/sinfo/eventdeck/blob/ampersand/client/js/models/company.js#L139

**Comment by JGAntunes** [comment]
Dunno, have you tested it?

**Comment by xicombd** [comment]
@dmpaiva?

**Comment by dmpaiva** [comment]
Sorry for hte silence I've been off the grid since my laptop's transformer fried, just got a temporary replacement and I didn't test it because well.... no computer where i could do that and using a 3.5 inch android screen to do it is a bit bad... As @JGAntunes said it's not working and i can't check why :(

**Comment by xicombd** [comment]
Can you check it now @JGAntunes?
